### PR TITLE
Fix oauth tests

### LINKED ISSUE #12: Unit tests in "test_sites_routes.py" return false positives
Almost all test methods in [test_sites_routes.py](https://github.com/cuducos/findaconf/blob/user-roles/findaconf/tests/test_site_routes.py) execute their checks and assertions only when the `if valid_providers:` condition is fulfilled.

But, at this moment, in 8 out of 12 tests present in the file, that condition is not fulfilled, and without an `else:` option, the tests simply don't do anything, neither raising assertion errors, thus they are all evaluated as "passed".

-
A simple way to reproduce this bug in the aforementioned file, is to add this lines
```
else:
    self.assertEqual(1,2,'valid_providers: {}'.format(valid_providers))
```
at the end of each method that uses the `if valid_providers:` statement.

-
**Side note:** this bug could be hidden also in other test files. A wider and deeper search is *strongly* required.

### PR DESCRIPTION
**Pull request by cuducos**
Fix #12

### CODE REVIEW

**Comment by lorenzo-pasa** [comment]
There is still something to fix about the oauth tests.

*test_login_with_remember_me* returns an error.

The problem is [line 214](https://github.com/cuducos/findaconf/blob/fix-oauth-tests/findaconf/tests/test_site_routes.py#L214): the query doesn't find anything and we end up with `user = None`
(and the assertion on line 215 returns an `AttributeError: 'NoneType' object has no attribute 'id'`)

-
Tracking down the problem, I found that the **real culprit** is [this check](https://github.com/cuducos/findaconf/blob/fix-oauth-tests/findaconf/blueprints/site/views.py#L63) in the `login_process()` view.

The workflow is this:
* we reach that view from our test (also enabling the _follow_redirects_ flag)
* the `if form.validate_on_submit():` check fails
* we jump to the `abort(404)` at the end of the view, actually skipping all the code into the view

Because we don't reach the `login()` view (the only place where the user is created), we come back to the test without a user in the DB.

**Comment by lorenzo-pasa** [comment]
The problem starts from [the validator](https://github.com/cuducos/findaconf/blob/fix-oauth-tests/findaconf/forms.py#L12) for the *provider* field of the LoginForm.

That validator gets its own list of valid providers from the OAuthProvider object at the very beginning of the test suite running... probably *even before the test suite start running*.

The result is:
* **form:** the list of valid providers is populated using the data in the `.env` file and in the `config.py` file _of the application_
* **test**: the fake provider used during the test is the one defined in the `tests/config.py` file

For this reason, our fake provider (defined [here](https://github.com/cuducos/findaconf/blob/fix-oauth-tests/findaconf/tests/config.py#L27) in the test configuration) is not in the list of the valid providers that the form has.
Therefore, the `form.validate_on_submit()` return False.

As a confirmation of this, simply changing the name of our fake provider with the same of one of the providers present in the `.env` and `config.py` files, make the test pass.

**Comment by cuducos** [comment]
Fixed :)

**Comment by lorenzo-pasa** [comment]
My commit of an enhanced test (e26aeef2dce571315f49287ec23698865fb4a590) is a suggestion, open to discussion ;)

Other than that, I checked this PR and for me it's ready to be merged !

(Actually, [this test](https://github.com/cuducos/findaconf/blob/fix-oauth-tests/findaconf/tests/test_file_routes.py#L36) fails, but fixing it should be quite simple and seems a little off-topic in this branch, IMHO)

**Comment by lorenzo-pasa** [comment]
The correct and updated mimetypes are listed in the [IANA website](http://www.iana.org/assignments/media-types/media-types.xhtml#application).

**Comment by cuducos** [comment]
You removed one of the mimetype my Linux returns:

```
AssertionError: 'application/x-font-woff' not found in ['application/vnd.ms-fontobject', 'application/octet-stream', 'application/font-woff', 'application/font-sfnt', 'image/svg+xml']
```

Standards are there, but following them is a recomendation, not a compulsory thing. Thus shall we add `application/x-font-woff` back or just dismiss mimetype check completely to avoid this mess?

**Comment by lorenzo-pasa** [comment]
Sorry for the removed mimetype :(
I checked before changing the code, and the `application/font-woff` should be "the" standard.. but in the browsers and mimetypes world, "standard" is a very misleading concept.

As a short term solution, we can add `application/x-font-woff` back and have both in the list without a problem (and this is the way I should have updated the test...)

For a long term solution, we can decide if dismiss the mimetype check or replace it with something more efficient.

**Comment by cuducos** [comment]
Done and mergin…

**Pull request merged**
